// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0k08t-Y_2uT60pa1JQugHW1M4yJhCWEM',
    appId: '1:806737479808:web:52c648bafed807564ebe65',
    messagingSenderId: '806737479808',
    projectId: 'aura-1999',
    authDomain: 'aura-1999.firebaseapp.com',
    databaseURL: 'https://aura-1999-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aura-1999.firebasestorage.app',
    measurementId: 'G-79E5H3NL5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPX_DOhkvKIVCqnnswVzkULOuCSurzC6o',
    appId: '1:806737479808:android:401675764c7d0d6a4ebe65',
    messagingSenderId: '806737479808',
    projectId: 'aura-1999',
    databaseURL: 'https://aura-1999-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aura-1999.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRBa2c2xaCUK7F8Ph-yaF8EqT8cLg2NzU',
    appId: '1:806737479808:ios:713931b49113b9f24ebe65',
    messagingSenderId: '806737479808',
    projectId: 'aura-1999',
    databaseURL: 'https://aura-1999-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aura-1999.firebasestorage.app',
    iosBundleId: 'com.example.aura',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRBa2c2xaCUK7F8Ph-yaF8EqT8cLg2NzU',
    appId: '1:806737479808:ios:713931b49113b9f24ebe65',
    messagingSenderId: '806737479808',
    projectId: 'aura-1999',
    databaseURL: 'https://aura-1999-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aura-1999.firebasestorage.app',
    iosBundleId: 'com.example.aura',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0k08t-Y_2uT60pa1JQugHW1M4yJhCWEM',
    appId: '1:806737479808:web:13defe83657b72884ebe65',
    messagingSenderId: '806737479808',
    projectId: 'aura-1999',
    authDomain: 'aura-1999.firebaseapp.com',
    databaseURL: 'https://aura-1999-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aura-1999.firebasestorage.app',
    measurementId: 'G-6HKQCV33VJ',
  );
}
